# Generated by Django 5.0.4 on 2024-05-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('contact_details', models.TextField()),
                ('address', models.TextField()),
                ('vendor_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('on_time_delivery_rate', models.FloatField(blank=True, default=0.0)),
                ('quality_rating_avg', models.FloatField(blank=True, default=0.0)),
                ('average_response_time', models.FloatField(blank=True, default=0.0)),
                ('fulfillment_rate', models.FloatField(blank=True, default=0.0)),
            ],
        ),
    ]
